Repository vibinex/vibinex-server, pull requests merged in 2023-09, with the labels that each got.

#128 bug fix: getEmailAliases fix for Bitbucket
  utils/providerAPI/getEmailAliases.ts
Labels: bugs

#115 Implement onprem app installation for bitbucket
  next.config.js
  package-lock.json
  package.json
  pages/api/bitbucket/callbacks/install.ts
  pages/api/bitbucket/callbacks/webhook.ts
  pages/api/extension/relevant.ts
  pages/api/hunks.ts
  pages/api/rustApp/setup.ts
  types/PubSubMessage.d.ts
  utils/db/relevance.ts
  utils/db/users.ts
  utils/pubsub/pubsubClient.ts
Labels: feature, infra

#142 Tech debt: resolved several sonar-cloud issues
  components/AppBar.tsx
  components/Button.tsx
  components/LoadingOverlay.tsx
  components/LoginLogout.tsx
  mdx-components.tsx
  pages/api/auth/[...nextauth].ts
  pages/download.tsx
  pages/nextjs_intro.tsx
  pages/upload.tsx
  public/buttonImage/Non-Retina/signInLargeActive.png
  public/buttonImage/Non-Retina/signInLargeDefault.png
  public/buttonImage/Non-Retina/signInLargeHover.png
  public/buttonImage/Non-Retina/signInSmallActive.png
  public/buttonImage/Non-Retina/signInSmallDefault.png
  public/buttonImage/Non-Retina/signInSmallHover.png
  public/buttonImage/Retina/signInLargeActive.png
  public/buttonImage/Retina/signInLargeDefault.png
  public/buttonImage/Retina/signInLargeHover.png
  public/buttonImage/Retina/signInSmallActive.png
  public/buttonImage/Retina/signInSmallDefault.png
  public/buttonImage/Retina/signInSmallHover.png
  public/linux_instruction/lstep2.gif
  public/linux_instruction/lstep3.gif
  public/linux_instruction/lstep4.gif
  public/linux_instruction/lstep5.gif
  public/linux_instruction/lstep6.gif
  public/linux_instruction/lstep7.gif
  public/linux_instruction/lstep8.gif
  public/mac_instruction/mstep1.gif
  public/mac_instruction/mstep2.gif
  public/mac_instruction/mstep3.gif
  public/mac_instruction/mstep4.gif
  public/mac_instruction/mstep5.gif
  public/mac_instruction/mstep6.gif
  public/mac_instruction/mstep7.gif
  public/standingMan.png
  public/vercel.svg
  public/windows_instruction/wstep2.gif
  public/windows_instruction/wstep3.gif
  public/windows_instruction/wstep4.gif
  public/windows_instruction/wstep5.gif
  public/windows_instruction/wstep6.gif
  public/windows_instruction/wstep7.gif
  utils/db/users.ts
  utils/providerAPI/Bitbucket.ts
Labels: tech debt
